### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by Jared-goodman** [bobmonkeywarts/pihatwebsite#2]
![image](https://user-images.githubusercontent.com/10575862/29503593-b7bc143e-85ed-11e7-937f-bc951494c0d7.png)
this is a picture of the code

**Comment by Jared-goodman** [comment]
![slightly less spaghetti](https://user-images.githubusercontent.com/10575862/29506083-af539324-85fe-11e7-8981-961c60a75dd6.png)
now it looks like this because I just spent 2 hours cleaning it up (I timed it) and now there is slightly less spaghetti ¯\\\_(ツ)_/¯

**Comment by midn1** [comment]
Good job

**Comment by Jared-goodman** [comment]
thx

**Comment by Jared-goodman** [comment]
`u/gru_spycrab fixed it, don't worry https://www.reddit.com/r/ProgrammerHumor/comments/6v4p00/i_spent_2_hours_last_night_removing_spaghetti/dlxv8zp/

**Comment by midn1** [comment]
![guud](https://i.ytimg.com/vi/RKdd7fLwszg/maxresdefault.jpg)  
good
